In [25]:
import pandas as pd

df = pd.read_csv('GOOG.csv')
df.head()

,Price,Adj Close,Close,High,Low,Open,Volume
0,2024-01-02,139.218109,139.559998,140.615005,137.740005,139.600006,20071900
1,2024-01-03,140.016144,140.360001,141.089996,138.429993,138.600006,18974300
2,2024-01-04,137.701828,138.039993,140.634995,138.009995,139.850006,18253300
3,2024-01-05,137.053421,137.389999,138.809998,136.850006,138.352005,15433200
4,2024-01-08,140.185715,140.529999,140.639999,137.880005,138.000000,17645300

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      233 non-null    object
 1   Adj Close  233 non-null    float64
 2   Close      233 non-null    float64
 3   High       233 non-null    float64
 4   Low        233 non-null    float64
 5   Open       233 non-null    float64
 6   Volume     233 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 12.9+ KB

In [27]:
df_short = pd.read_csv('GOOG.csv', usecols=['Adj Close', 'Close', 'Price'])
df_short.head()

        Price   Adj Close       Close
0  2024-01-02  139.218109  139.559998
1  2024-01-03  140.016144  140.360001
2  2024-01-04  137.701828  138.039993
3  2024-01-05  137.053421  137.389999
4  2024-01-08  140.185715  140.529999

In [36]:
df['Low'] = df['Low'].astype(float)
df_filtered = df[df['Adj Close'] < 139]
df_filtered

,Price,Adj Close,Close,High,Low,Open,Volume
2,2024-01-04,137.701828,138.039993,140.634995,138.009995,139.850006,18253300
3,2024-01-05,137.053421,137.389999,138.809998,136.850006,138.352005,15433200
37,2024-02-26,138.410095,138.750000,143.839996,138.740005,143.449997,33513000
39,2024-02-28,137.093323,137.429993,139.279999,136.639999,139.100006,30628700
41,2024-03-01,137.741745,138.080002,140.000000,137.975006,139.610001,28522000
42,2024-03-04,133.871231,134.199997,136.630005,132.860001,136.539993,43571500
43,2024-03-05,133.452271,133.779999,134.020004,131.550003,132.740005,28447600
44,2024-03-06,132.235245,132.559998,134.740005,131.949997,134.240005,23175200
45,2024-03-07,134.908691,135.240005,135.820007,132.660004,133.889999,24107300
46,2024-03-08,135.956116,136.289993,138.985001,134.800003,135.035004,26472400
47,2024-03-11,138.599625,138.940002,139.979996,137.070007,137.070007,22536400

In [37]:
df['Low'] = df['Low'].astype(float)
df_filtered = df[df['Adj Close'] < 139]
df_filtered.shape

(11, 7)

In [38]:
df.isna().sum

<bound method DataFrame.sum of      Price  Adj Close  Close   High    Low   Open  Volume
0    False      False  False  False  False  False   False
1    False      False  False  False  False  False   False
2    False      False  False  False  False  False   False
3    False      False  False  False  False  False   False
4    False      False  False  False  False  False   False
..     ...        ...    ...    ...    ...    ...     ...
228  False      False  False  False  False  False   False
229  False      False  False  False  False  False   False
230  False      False  False  False  False  False   False
231  False      False  False  False  False  False   False
232  False      False  False  False  False  False   False

[233 rows x 7 columns]>